apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-secrets-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-secrets-exporter.labels" . | nindent 4 }}
data:
  secrets.json: {{ .Values.secrets | toJson | quote }}
