apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-server-spectator-chart.fullname" . }}
  labels:
    {{- include "osu-server-spectator-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-server-spectator-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osu-server-spectator-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-server-spectator-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: oauth-public-key-secret
          secret:
            {{- if .Values.useSharedSecretsFromOsuWebChart }}
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
            {{- else }}
            secretName: {{ include "osu-server-spectator-chart.fullname" . }}-oauth-public-key
            {{- end }}
            items:
              - key: oauth-public.key
                path: oauth-public.key
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ toYaml . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/oauth-public.key
              name: oauth-public-key-secret
              subPath: oauth-public.key
              readOnly: true
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          envFrom:
            - secretRef:
                {{- if .Values.useSharedSecretsFromOsuWebChart }}
                name: {{ include "osu-web-chart.fullname" . }}-shared
                {{- else }}
                name: {{ include "osu-server-spectator-chart.fullname" . }}
                {{- end }}
                optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
