{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-server-spectator-chart.fullname" . }}-oauth-public-key
  labels:
    {{- include "osu-server-spectator-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth-public.key: {{- printf " |%s" (required "Missing Laravel oauthPublicKey" .Values.config.laravel.oauth.publicKey | nindent 4) }}
{{- end }}
