apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kubernetes-cloudflare-certificates-uploader.fullname" . }}
  labels:
    {{- include "kubernetes-cloudflare-certificates-uploader.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "kubernetes-cloudflare-certificates-uploader.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ include "kubernetes-cloudflare-certificates-uploader.fullname" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
