apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-cloudflare-certificates-uploader.fullname" . }}
  labels:
    {{- include "kubernetes-cloudflare-certificates-uploader.labels" . | nindent 4 }}
stringData:
  SECRET_NAME: {{ required "Secret name is required" .Values.config.secretName | quote }}
  API_TOKEN: {{ required "Cloudflare API Token is required" .Values.config.apiToken | quote }}
  ZONE_ID: {{ required "Cloudflare Zone ID is required" .Values.config.zoneId | quote }}
