apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osu-elastic-indexer-chart.fullname" . }}
  labels:
    {{- include "osu-elastic-indexer-chart.labels" . | nindent 4 }}
data:
  {{- if not (eq nil .Values.config.elasticIndexer.batchSize) }}
  BATCH_SIZE: {{ .Values.config.elasticIndexer.batchSize | quote }}
  {{- end }}
  {{- if not (eq nil .Values.config.elasticIndexer.bufferSize) }}
  BUFFER_SIZE: {{ .Values.config.elasticIndexer.bufferSize | quote }}
  {{- end }}
  {{- if not (eq nil .Values.config.elasticIndexer.sentryDsn) }}
  SENTRY_DSN: {{ .Values.config.elasticIndexer.sentryDsn | quote }}
  {{- end }}
  SCHEMA: {{ required "Schema version is required" .Values.config.elasticIndexer.schema | quote }}
