{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-elastic-indexer-chart.fullname" . }}
  labels:
    {{- include "osu-elastic-indexer-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_CONNECTION_STRING: {{ required "Missing db connection string" .Values.config.db.connectionString | quote }}
  ES_HOST: {{ required "Missing elasticsearch host" .Values.config.elasticsearch.host | quote }}
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.host | quote }}
  {{- if not (eq nil .Values.config.elasticIndexer.prefix) }}
  ES_INDEX_PREFIX: {{ .Values.config.elasticIndexer.prefix | quote }}
  {{- end }}
{{- end }}
