{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-elastic-indexer-chart.fullname" . }}
  labels:
    {{- include "osu-elastic-indexer-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.db.connectionString }}
  DB_CONNECTION_STRING: {{ .Values.config.db.connectionString | quote }}
  {{- end }}
  DB_HOST: {{ .Values.config.db.host | quote }}
  DB_USER: {{ .Values.config.db.username | quote }}
  DB_PASS: {{ .Values.config.db.password | quote }}
  DB_NAME: {{ .Values.config.db.database | quote }}
  ES_HOST: {{ required "Missing elasticsearch host URI" .Values.config.elasticsearch.hostUri | quote }}
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.host | quote }}
  {{- if not (eq nil .Values.config.elasticIndexer.prefix) }}
  ES_INDEX_PREFIX: {{ .Values.config.elasticIndexer.prefix | quote }}
  {{- end }}
{{- end }}
