apiVersion: v1
kind: Secret
metadata:
  name: {{ include "form-auth-chart.fullname" . }}
  labels:
    {{- include "form-auth-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  cookiesSecret: {{ required "Missing cookies secret" .Values.secrets.cookies | quote }}
  tokensPrivateKey: {{ required "Missing tokens private key" .Values.secrets.tokens.privateKey | quote }}
  tokensPublicKey: {{ required "Missing tokens public key" .Values.secrets.tokens.publicKey | quote }}
  osuClientId: {{ required "Missing osu! OAuth Client ID" .Values.secrets.osu.clientId | quote }}
  osuClientSecret: {{ required "Missing osu! OAuth Client Secret" .Values.secrets.osu.clientSecret | quote }}
