apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-nginx-proxy-chart.fullname" . }}
  labels:
    {{- include "s3-nginx-proxy-chart.labels" . | nindent 4 }}
type: Opaque
data:
  secrets.json: {{ .Values.secrets | toJson | quote }}
