apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osu-queue-score-statistics-chart.fullname" . }}
  labels:
    {{- include "osu-queue-score-statistics-chart.labels" . | nindent 4 }}
data:
  {{- if not (eq nil .Values.config.queueScoreStatistics.usersTable) }}
  DB_USERS_TABLE: {{ .Values.config.queueScoreStatistics.usersTable | quote }}
  {{- end }}
  SCHEMA: {{ required "Schema version is required" .Values.config.queueScoreStatistics.schema | quote }}
  {{- if .Values.config.queueScoreStatistics.processUserTotals }}
  PROCESS_USER_TOTALS: "1"
  {{- end }}
