apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-queue-score-statistics-chart.fullname" . }}
  labels:
    {{- include "osu-queue-score-statistics-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-queue-score-statistics-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osu-queue-score-statistics-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-queue-score-statistics-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - dotnet
            - osu.Server.Queues.ScoreStatisticsProcessor.dll
            - queue
            - watch
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          envFrom:
            - secretRef:
                {{- if .Values.useSharedSecretsFromOsuWebChart }}
                name: {{ include "osu-web-chart.fullname" . }}-shared
                {{- else }}
                name: {{ include "osu-queue-score-statistics-chart.fullname" . }}
                {{- end }}
                optional: false
            - configMapRef:
                name: {{ include "osu-queue-score-statistics-chart.fullname" . }}
                optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
