{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-beatmap-difficulty-lookup-cache-chart.fullname" . }}
  labels:
    {{- include "osu-beatmap-difficulty-lookup-cache-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.beatmapDifficultyLookupCache.env }}
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.beatmapDifficultyLookupCache.env }}"
  {{- end }}
  {{- if .Values.config.beatmapDifficultyLookupCache.useDatabaseLookups }}
  USE_DATABASE_LOOKUPS: "true"
  {{- if .Values.config.db.host }}
  DB_HOST: {{ required "Missing db host" .Values.config.db.host }}
  {{- end }}
  {{- if .Values.config.db.username }}
  DB_USER: {{ .Values.config.db.username }}
  {{- end }}
  {{- if .Values.config.db.port }}
  DB_PORT: {{ .Values.config.db.port }}
  {{- end }}
  {{- end }}
{{- end }}
