apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-octane
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-web-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osu-web-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/docker/deployment/entrypoint.sh
            - octane
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            # httpGet:
              # path: /home
              # port: http
          readinessProbe:
            tcpSocket:
              port: http
            # httpGet:
              # path: /home
              # port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/storage/passport/oauth-public.key
              name: oauth-public-key-secret
              subPath: laravelOauthPublicKey
              readOnly: true
            - mountPath: /app/storage/passport/oauth-private.key
              name: oauth-private-key-secret
              subPath: laravelOauthPrivateKey
              readOnly: true
            - mountPath: /app/.env
              name: env-secret
              subPath: .env
              readOnly: true
      volumes:
        - name: oauth-public-key-secret
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
            items:
              - key: laravelOauthPublicKey
                path: oauth-public.key
        - name: oauth-private-key-secret
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}
            items:
              - key: laravelOauthPrivateKey
                path: oauth-private.key
        - name: env-secret
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}
            items:
              - key: .env
                path: .env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
