apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-octane
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ sha256sum (printf "%s-%s-%s" .Values.config.laravel.oauth.privateKey .Values.config.laravel.oauth.publicKey (include "osu-web-chart.env-vars" .)) }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-web-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ sha256sum (printf "%s-%s-%s" .Values.config.laravel.oauth.privateKey .Values.config.laravel.oauth.publicKey (include "osu-web-chart.env-vars" .)) }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "osu-web-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/docker/deployment/entrypoint.sh
            - octane
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            # httpGet:
              # path: /home
              # port: http
          readinessProbe:
            tcpSocket:
              port: http
            # httpGet:
              # path: /home
              # port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/storage/oauth-public.key
              name: secret-shared-oauth-public-key
              subPath: oauth-public.key
              readOnly: true
            - mountPath: /app/storage/oauth-private.key
              name: secret-oauth-private-key
              subPath: oauth-private.key
              readOnly: true
            {{- range $storageName, $storage := .Values.config.storage }}
            {{- if or (eq "local" $storage.driver) (eq "local-avatar" $storage.driver) }}
            - mountPath: /app/public/uploads{{- if not (eq "general" $storageName) -}}-{{ $storageName }}{{- end }}
              name: pvc-{{ $storageName }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "osu-web-chart.fullname" . }}-env
      volumes:
        - name: secret-shared-oauth-public-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
        - name: secret-oauth-private-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-oauth-private-key
        {{- range $storageName, $storage := .Values.config.storage }}
        {{- if or (eq "local" $storage.driver) (eq "local-avatar" $storage.driver) }}
        - name: pvc-{{ $storageName }}
          persistentVolumeClaim:
            claimName: {{ include "osu-web-chart.fullname" $ }}-{{ $storageName }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
