{{- $fullName := include "osu-web-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $apiVersion := "" -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- $apiVersion = "networking.k8s.io/v1" -}}
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- else -}}
  {{- $apiVersion = "extensions/v1beta1" -}}
{{- end -}}

{{- $config := list
  (dict
    "ingressConfig" .Values.ingress
    "suffix" ""
    "serviceSuffix" ""
  )
  (dict
    "ingressConfig" .Values.ingressAssets
    "suffix" "-assets"
    "serviceSuffix" "-assets"
  )
-}}
{{- range $config := $config -}}
{{- with $ }}
{{- if $config.ingressConfig.enabled }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}{{ $config.suffix }}
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
  {{- with $config.ingressConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $config.ingressConfig.tls }}
  tls:
    {{- range $config.ingressConfig.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $config.ingressConfig.hosts }}
    - host: {{ (include "osu-web.ingress-host" (dict "host" .host "defaultHost" (include "osu-web.laravelAppUrl" $))) | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if not (eq $apiVersion "networking.k8s.io/v1") }}
              serviceName: {{ $fullName }}{{ $config.serviceSuffix }}
              servicePort: {{ $svcPort }}
              {{- else }}
              service:
                name: {{ $fullName }}{{ $config.serviceSuffix }}
                port:
                  name: http
              {{- end }}
          {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
