{{- if .Values.config.db.migrate -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-migrate
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
    tier: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 16 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              ln -s /secret-shared-oauth-public-key/oauth-public.key /app/storage/oauth-public.key && \
              ln -s /secret/oauth-private.key /app/storage/oauth-private.key && \
              ln -s /secret/.env /app/.env && \
              su osuweb -c '/app/artisan migrate --force'
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          volumeMounts:
            - mountPath: /secret
              name: secret
              readOnly: true
            - mountPath: /secret-shared-oauth-public-key
              name: secret-shared-oauth-public-key
              readOnly: true
      volumes:
        - name: secret-shared-oauth-public-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key-migrate
        - name: secret
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-migrate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end -}}
