{{- if or .Values.config.db.insertOsuWebBuild.enabled .Values.config.db.migrate -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-migrate
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
    tier: migrate
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{ $commands := list }}
            {{- if .Values.config.db.insertOsuWebBuild.enabled -}}
            {{- $commands = append $commands (printf "%s%s" "/app/artisan builds:create --stream-id=" (toString .Values.config.db.insertOsuWebBuild.streamId)) -}}
            {{- end -}}
            {{- if .Values.config.db.migrate -}}
            {{- $commands = append $commands "/app/artisan migrate --force" -}}
            {{- end -}}
            - /bin/sh
            - -c
            - {{ join " && " $commands }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/storage/oauth-public.key
              name: secret-shared-oauth-public-key
              subPath: oauth-public.key
              readOnly: true
            - mountPath: /app/storage/oauth-private.key
              name: secret-oauth-private-key
              subPath: oauth-private.key
              readOnly: true
          env:
            - name: DATADOG_STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: {{ include "osu-web-chart.fullname" . }}-env-migrate
      volumes:
        - name: secret-shared-oauth-public-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key-migrate
        - name: secret-oauth-private-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-oauth-private-key-migrate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
