{{- if .Values.podDisruptionBudget.enabled }}
{{- $apiVersion := "" -}}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- $apiVersion = "policy/v1" -}}
{{- else -}}
  {{- $apiVersion = "policy/v1beta1" -}}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "osu-web-chart.fullname" . }}
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "osu-web-chart.selectorLabels" . | nindent 6 }}
{{- end }}
