{{- $apiVersion := "" -}}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- $apiVersion = "policy/v1" -}}
{{- else -}}
  {{- $apiVersion = "policy/v1beta1" -}}
{{- end -}}

{{- $config := list
  (dict
    "pdbConfig" .Values.podDisruptionBudget
    "suffix" ""
    "includeOptions" (dict "component" "octane")
  )
  (dict
    "pdbConfig" .Values.assets.podDisruptionBudget
    "suffix" "-assets"
    "includeOptions" (dict "component" "assets")
  )
-}}
{{- range $config := $config -}}
{{- with $ }}
{{- if $config.pdbConfig.enabled }}
---
apiVersion: {{ $apiVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "osu-web-chart.fullname" . }}{{ $config.suffix }}
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" $config.includeOptions) | nindent 4 }}
spec:
{{- if $config.pdbConfig.minAvailable }}
  minAvailable: {{ $config.pdbConfig.minAvailable }}
{{- end }}
{{- if $config.pdbConfig.maxUnavailable }}
  maxUnavailable: {{ $config.pdbConfig.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "osu-web-chart.selectorLabels" (dict "root" . "options" $config.includeOptions) | nindent 6 }}
{{- end }}
{{- end -}}
{{- end -}}
