{{- $config := list
  (dict
    "suffix" ""
    "additionalLabels" (dict)
    "annotations" (dict)
  )
-}}
{{- if and .Values.config.upgradeJob.enabled (or .Values.config.upgradeJob.insertOsuWebBuild.enabled .Values.config.upgradeJob.migrate) -}}
{{- $config = append $config (dict
  "suffix" "-upgrade"
  "additionalLabels" (dict
    "tier" "upgrade"
  )
  "annotations" (dict
    "helm.sh/hook" "post-install,pre-upgrade"
    "helm.sh/hook-weight" "-20"
    "helm.sh/hook-delete-policy" "before-hook-creation"
    "helm.sh/resource-policy" "keep"
  )
) -}}
{{- end -}}
{{- if and .Values.config.seedingJob.enabled (and .Values.config.upgradeJob.enabled .Values.config.upgradeJob.migrate) -}}
{{- $config = append $config (dict
  "suffix" "-seed"
  "additionalLabels" (dict
    "tier" "seed"
  )
  "annotations" (dict
    "helm.sh/hook" "post-install"
    "helm.sh/hook-weight" "-20"
    "helm.sh/hook-delete-policy" "hook-succeeded"
    "helm.sh/resource-policy" "keep"
  )
) -}}
{{- end -}}
{{- range $config := $config -}}
{{- with $ }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-env{{ $config.suffix }}
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict)) | nindent 4 }}
    {{- range $key, $value := $config.additionalLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{- include "osu-web-chart.env-vars" . | nindent 2 -}}
{{- end }}
{{- end }}
