{{- $config := list
  (dict
    "suffix" ""
    "additionalLabels" (dict)
    "annotations" (dict)
  )
-}}
{{- if .Values.config.db.migrate -}}
{{- $config = append $config (dict
  "suffix" "-migrate"
  "additionalLabels" (dict
    "tier" "migrate"
  )
  "annotations" (dict
    "helm.sh/hook" "post-install,pre-upgrade"
    "helm.sh/hook-weight" "-10"
    "helm.sh/hook-delete-policy" "hook-succeeded"
  )
) -}}
{{- end -}}
{{- range $config := $config -}}
{{- with $ }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key{{ $config.suffix }}
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
    {{- range $key, $value := $config.additionalLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  oauth-public.key: {{- printf " |%s" (required "Missing Laravel oauthPublicKey" .Values.config.laravel.oauth.publicKey | nindent 4) }}
{{- end }}
{{- end }}
