apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-shared
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.laravel.debug }}
  APP_DEBUG: "{{ .Values.config.laravel.debug }}"
  {{- end }}
  APP_ENV: {{ required "Missing app env" .Values.config.laravel.env }}
  {{- if .Values.config.spectatorServer.env }}
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.spectatorServer.env }}"
  {{- end }}
  DB_DATABASE: {{ include "osu-web.databaseName" . | quote }}
  DB_HOST: {{ include "osu-web.databaseHost" . | quote }}
  {{- if (include "osu-web.databasePassword" .) }}
  DB_PASSWORD: {{ include "osu-web.databasePassword" . | quote }}
  {{- end }}
  DB_USER: {{ .Values.config.db.user }}
  {{- if .Values.config.dbName.chat }}
  DB_NAME_CHAT: {{ .Values.config.dbName.chat }}
  {{- end }}
  APP_KEY: "{{ required "Missing Laravel appKey" .Values.config.laravel.appKey }}"
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.app.host }}
  {{- if .Values.config.redis.app.port }}
  REDIS_PORT: "{{ .Values.config.redis.app.port }}"
  {{- end }}
  NOTIFICATION_REDIS_HOST: {{ required "Missing redis notification host" .Values.config.redis.notification.host }}
  {{- if .Values.config.redis.notification.port }}
  NOTIFICATION_REDIS_PORT: "{{ .Values.config.redis.notification.port }}"
  {{- end }}
