apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth-private.key: {{- printf " |%s" (required "Missing Laravel oauthPrivateKey" .Values.config.laravel.oauth.privateKey | nindent 4) }}
  .env: |
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_URL" "value" (include "osu-web.laravelAppUrl" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_ENV" "value" .Values.config.laravel.env) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_DEBUG" "value" .Values.config.laravel.debug) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_KEY" "value" .Values.config.laravel.appKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_SENTRY" "value" .Values.config.laravel.sentry.url) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "APP_SENTRY_PUBLIC" "value" .Values.config.laravel.sentry.public_url) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "DB_HOST" "value" (include "osu-web.databaseHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DB_DATABASE" "value" (include "osu-web.databaseName" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DB_USERNAME" "value" (include "osu-web.databaseUsername" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DB_PASSWORD" "value" (include "osu-web.databasePassword" .)) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "REDIS_HOST" "value" (include "osu-web.redisAppHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "REDIS_PORT" "value" (include "osu-web.redisAppPort" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "REDIS_DB" "value" (include "osu-web.redisAppDb" .)) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "CACHE_REDIS_HOST" "value" (include "osu-web.redisCacheHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CACHE_REDIS_PORT" "value" (include "osu-web.redisCachePort" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CACHE_REDIS_DB" "value" (include "osu-web.redisCacheDb" .)) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "MEMCACHED_PERSISTENT_ID" "value" .Values.config.memcache.persistent_id) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MEMCACHED_USERNAME" "value" .Values.config.memcache.username) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MEMCACHED_PASSWORD" "value" .Values.config.memcache.password) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MEMCACHED_HOST" "value" .Values.config.memcache.host) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MEMCACHED_PORT" "value" .Values.config.memcache.port) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "BROADCAST_DRIVER" "value" .Values.config.laravel.log.driver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CACHE_DRIVER" "value" .Values.config.laravel.cache.driver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CACHE_DRIVER_LOCAL" "value" .Values.config.laravel.cache.localDriver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SESSION_DRIVER" "value" .Values.config.laravel.session.driver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SESSION_DOMAIN" "value" .Values.config.laravel.session.domain) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SESSION_SECURE_COOKIE" "value" .Values.config.laravel.session.secureCookie) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_DRIVER" "value" .Values.config.mail.driver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_HOST" "value" .Values.config.mail.host) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_PORT" "value" .Values.config.mail.port) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_ENCRYPTION" "value" .Values.config.mail.encryption) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_USERNAME" "value" .Values.config.mail.username) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "MAIL_PASSWORD" "value" .Values.config.mail.password) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "SHARED_INTEROP_SECRET" "value" .Values.config.laravel.legacy.sharedInteropSecret) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "FILESYSTEM_DISK" "value" .Values.config.storage.general.driver) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "BM_PROCESSOR_MIRRORS" "value" .Values.config.beatmapsProcessor.mirrors) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "BM_PROCESSOR_THUMBNAILER" "value" .Values.config.beatmapsProcessor.thumbnailer) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "BM_PROCESSOR_SENTRY" "value" .Values.config.beatmapsProcessor.sentry) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_KEY" "value" .Values.config.storage.general.s3.key) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_SECRET" "value" .Values.config.storage.general.s3.secret) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_REGION" "value" .Values.config.storage.general.s3.region) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_BUCKET" "value" .Values.config.storage.general.s3.bucket) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_BASE_URL" "value" .Values.config.storage.general.s3.baseUrl) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_MINI_URL" "value" .Values.config.storage.general.s3.miniUrl) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_AVATAR_KEY" "value" .Values.config.storage.avatar.s3.key) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_AVATAR_SECRET" "value" .Values.config.storage.avatar.s3.secret) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_AVATAR_REGION" "value" .Values.config.storage.avatar.s3.region) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "S3_AVATAR_BUCKET" "value" .Values.config.storage.avatar.s3.bucket) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "AVATAR_STORAGE" "value" .Values.config.storage.avatar.driver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "AVATAR_CACHE_PURGE_PREFIX" "value" .Values.config.storage.avatar.s3.cachePurgePrefix) }}

    # Either "s3" or "local".
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORE_REPLAYS_STORAGE" "value" .Values.config.storage.replay.driver) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "QUEUE_DRIVER" "value" .Values.config.laravel.queueDriver) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CAMO_KEY" "value" .Values.config.laravel.camo.key) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CAMO_PREFIX" "value" .Values.config.laravel.camo.prefix) }}

    PASSPORT_KEY_PATH=/app/storage/passport

    {{ template "osu-web-chart.dotenv-var" (dict "name" "GITHUB_TOKEN" "value" .Values.config.laravel.githubToken) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_ENABLED" "value" .Values.config.laravel.datadog.enabled) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_PREFIX" "value" .Values.config.laravel.datadog.prefix) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_API_KEY" "value" .Values.config.laravel.datadog.apiKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_APP_KEY" "value" .Values.config.laravel.datadog.appKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_HOST" "value" .Values.config.laravel.datadog.host) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_STATSD_HOST" "value" .Values.config.laravel.datadog.statsd.host) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_STATSD_PORT" "value" .Values.config.laravel.datadog.statsd.port) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "DATADOG_STATSD_SOCKET" "value" .Values.config.laravel.datadog.statsd.socket) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "CHANGELOG_GITHUB_TOKEN" "value" .Values.config.laravel.changelogGithubToken) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYMENT_SANDBOX" "value" .Values.config.laravel.payments.sandbox) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "SHOPIFY_DOMAIN" "value" .Values.config.laravel.payments.shopify.domain) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SHOPIFY_STOREFRONT_TOKEN" "value" .Values.config.laravel.payments.shopify.storeFrontToken) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SHOPIFY_WEBHOOK_KEY" "value" .Values.config.laravel.payments.shopify.webhookKey) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "STORE_NOTIFICATION_CHANNEL" "value" .Values.config.laravel.notifications.store.channel) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "STORE_NOTIFICATIONS_QUEUE" "value" .Values.config.laravel.notifications.store.queue) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "STORE_STALE_DAYS" "value" .Values.config.laravel.payments.storeStaleDays) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYPAL_URL" "value" .Values.config.laravel.payments.paypal.url) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYPAL_MERCHANT_ID" "value" .Values.config.laravel.payments.paypal.merchantId) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYPAL_CLIENT_ID" "value" .Values.config.laravel.payments.paypal.clientId) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYPAL_CLIENT_SECRET" "value" .Values.config.laravel.payments.paypal.clientSecret) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "PAYPAL_NO_SHIPPING_EXPERIENCE_PROFILE_ID" "value" .Values.config.laravel.payments.paypal.noShippingExperienceProfileId) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "XSOLLA_API_KEY" "value" .Values.config.laravel.payments.xsolla.apiKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "XSOLLA_MERCHANT_ID" "value" .Values.config.laravel.payments.xsolla.merchantId) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "XSOLLA_PROJECT_ID" "value" .Values.config.laravel.payments.xsolla.projectId) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "XSOLLA_SECRET_KEY" "value" .Values.config.laravel.payments.xsolla.secretKey) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "CENTILI_API_KEY" "value" .Values.config.laravel.payments.centili.apiKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CENTILI_SECRET_KEY" "value" .Values.config.laravel.payments.centili.secretKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CENTILI_CONVERSION_RATE" "value" .Values.config.laravel.payments.centili.conversionRate) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "CENTILI_WIDGET_URL" "value" .Values.config.laravel.payments.centili.widgetUrl) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_HOST" "value" (include "osu-web.elasticsearchHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_SCORES_HOST" "value" (include "osu-web.elasticsearchScoresHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_INDEX_PREFIX" "value" .Values.config.elasticsearch.indexPrefix) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_CLIENT_TIMEOUT" "value" .Values.config.elasticsearch.clientTimeout) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_CLIENT_CONNECT_TIMEOUT" "value" .Values.config.elasticsearch.clientConnectTimeout) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "ES_SEARCH_TIMEOUT" "value" .Values.config.elasticsearch.searchTimeout) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "NOTIFICATION_QUEUE" "value" .Values.config.laravel.notifications.queue) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "NOTIFICATION_REDIS_HOST" "value" (include "osu-web.redisNotificationHost" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "NOTIFICATION_REDIS_PORT" "value" (include "osu-web.redisNotificationPort" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "NOTIFICATION_REDIS_DB" "value" (include "osu-web.redisNotificationDb" .)) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "NOTIFICATION_ENDPOINT" "value" (include "osu-web.notificationServerPublicUrl" .)) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "LOG_CHANNEL" "value" .Values.config.laravel.logChannel) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "#RECAPTCHA_SECRET" "value" .Values.config.laravel.recaptcha.secret) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "#RECAPTCHA_SITEKEY" "value" .Values.config.laravel.recaptcha.siteKey) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "#RECAPTCHA_THRESHOLD" "value" .Values.config.laravel.recaptcha.threshold) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "TWITCH_CLIENT_ID" "value" .Values.config.laravel.twitch.clientId) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "TWITCH_CLIENT_SECRET" "value" .Values.config.laravel.twitch.clientSecret) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORES_ES_CACHE_DURATION" "value" .Values.config.laravel.scores.cacheDuration) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORES_RANK_CACHE_LOCAL_SERVER" "value" .Values.config.laravel.scoresRankCache.localServer) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORES_RANK_CACHE_MIN_USERS" "value" .Values.config.laravel.scoresRankCache.minUsers) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORES_RANK_CACHE_SERVER_URL" "value" .Values.config.laravel.scoresRankCache.serverUrl) }}
    {{ template "osu-web-chart.dotenv-var" (dict "name" "SCORES_RANK_CACHE_TIMEOUT" "value" .Values.config.laravel.scoresRankCache.timeout) }}

    {{ template "osu-web-chart.dotenv-var" (dict "name" "BANCHO_BOT_USER_ID" "value" .Values.config.laravel.legacy.banchoBotUserId) }}

    {{ .Values.config.laravel.extraEnv }}
