apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  laravelOauthPublicKey: {{- printf " |%s" (required "Missing Laravel oauthPublicKey" .Values.config.laravel.oauth.publicKey | nindent 4) }}
