{{- if and .Values.config.seedingJob.enabled (and .Values.config.upgradeJob.enabled .Values.config.upgradeJob.migrate) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-seed
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict "component" "seed")) | nindent 4 }}
    tier: seed
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 16 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            # ES indexing needs to be done prior, otherwise seeding fails at UserSeeder due to missing indexes
            - |
              /app/artisan es:index-documents -n --yes && \
              /app/artisan db:seed --force && \
              /app/artisan es:create-search-blacklist -n && \
              /app/artisan es:index-wiki --create-only -n --yes
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          volumeMounts:
            - mountPath: /app/storage/oauth-public.key
              name: secret-shared-oauth-public-key
              subPath: oauth-public.key
              readOnly: true
            - mountPath: /app/storage/oauth-private.key
              name: secret-oauth-private-key
              subPath: oauth-private.key
              readOnly: true
          env:
            - name: DATADOG_STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OSU_API_KEY
              value: {{ .Values.config.seedingJob.apiKey | quote }}
          envFrom:
            - secretRef:
                name: {{ include "osu-web-chart.fullname" . }}-env-seed
      volumes:
        - name: secret-shared-oauth-public-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key-seed
        - name: secret-oauth-private-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-oauth-private-key-seed
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end -}}
