apiVersion: v1
kind: Service
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-assets
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict "component" "assets")) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osu-web-chart.selectorLabels" (dict "root" . "options" (dict "component" "assets")) | nindent 4 }}
